# Generated by Django 2.2.6 on 2021-01-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcalc',
            old_name='text',
            new_name='text_comment',
        ),
        migrations.AddField(
            model_name='postcalc',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=4),
            preserve_default=False,
        ),
    ]
